name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: java100 test
      id: java100-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: java100 test
        setup-command: ''
        command: mvn test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA100-TEST_RESULTS: "${{steps.java100-test.outputs.result}}"
      with:
        runners: java100-test
